// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlOHuc_Sp378h8dm_ket6SIWbFIiRb1jU',
    appId: '1:925262947453:web:be7b9e784f8e574808bd14',
    messagingSenderId: '925262947453',
    projectId: 'daily-calo',
    authDomain: 'daily-calo.firebaseapp.com',
    storageBucket: 'daily-calo.firebasestorage.app',
    measurementId: 'G-DS7QJW1T2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69fF-z02AO-awUeMWJTtRd60VgSTOJLo',
    appId: '1:925262947453:android:bbaf9c1c996a3a2f08bd14',
    messagingSenderId: '925262947453',
    projectId: 'daily-calo',
    storageBucket: 'daily-calo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_DjnX4VIiAFbXjToBgj7916GIMFtDJE',
    appId: '1:925262947453:ios:7cef65c35acea2b908bd14',
    messagingSenderId: '925262947453',
    projectId: 'daily-calo',
    storageBucket: 'daily-calo.firebasestorage.app',
    iosBundleId: 'com.example.dailyCalo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_DjnX4VIiAFbXjToBgj7916GIMFtDJE',
    appId: '1:925262947453:ios:7cef65c35acea2b908bd14',
    messagingSenderId: '925262947453',
    projectId: 'daily-calo',
    storageBucket: 'daily-calo.firebasestorage.app',
    iosBundleId: 'com.example.dailyCalo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlOHuc_Sp378h8dm_ket6SIWbFIiRb1jU',
    appId: '1:925262947453:web:8dc5c0ce615ebe0508bd14',
    messagingSenderId: '925262947453',
    projectId: 'daily-calo',
    authDomain: 'daily-calo.firebaseapp.com',
    storageBucket: 'daily-calo.firebasestorage.app',
    measurementId: 'G-FZ5T6VGE33',
  );
}
